# Generated by Django 5.1.7 on 2025-04-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_testclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
